### ISSUE TITLE
Option 'Display No Group column' not working?

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mmcquillan/lawsg#1]
It seems that the --ng option ('Display No Group column') isn't working.

Call:
`lawsg get "*" --starttime='12h ago' --filter="APPLOG" --ng --ns --nt --message-rtrim=1`

Result:
`/aws/lambda/PrintmapsMockBuildMap APPLOG 2018/04/25 08:07:40.365467 main.go:89: mockBuildMap() called ...`

The group name '_/aws/lambda/PrintmapsMockBuildMap_' is still printed.

**Comment by mmcquillan** [comment]
Sorry for the delay on seeing this. When you query by "*" and have multiple groups queried, I thought it best to override that and always show the group name. Would you prefer this not to be the case?

**Comment by mmcquillan** [comment]
@Klaus-Tockloth Just wanted to ping back on the above question.

**Comment by Klaus-Tockloth** [comment]
IMHO you should respect the user setting without adding any magic.

PS: Sorry for the late response.

**Comment by mmcquillan** [comment]
Changed the behavior, but will push a new release in a day or two.
