### ISSUE TITLE
Use Profile Instead of ENV

### ISSUE THREAD

**Issue by reskin89** [mmcquillan/lawsg#4]
Currently this only looks at the aws environment for config/to interact w/ the aws API.

Adding the ability for it to look at `AWS_DEFAULT_PROFILE` to direct it to `~/.aws/credentials` or for it to look for `[default]` in `~/.aws/credentials` if it doesn't find the necessary config in the environment would be helpful

**Comment by mmcquillan** [comment]
Thanks @reskin89, I'll check into this.

**Comment by mmcquillan** [comment]
@reskin89  Updated, published a release (0.4.0), and pushed the update to Homebrew. Let me know if you run into any problems.  Thanks!!!

**Comment by PeteW** [comment]
When I have 5+ different sets of aws credentials all present within my ~/.aws/credentials file, each credential is listed underneath a unique profile name e.g.:
```
[profile1]
aws_access_key_id = AXISAIDHFHRRIEU
aws_secret_access_key = falsiuh0a9ert32hag;ltg8y
aws_session_token = fauhrttgwargn=
aws_security_token = fasiouph3405

[profile2]
aws_access_key_id = AXISAIDHFHRRIEJ
aws_secret_access_key = falsiuh0a9ert32hag;ltg8y
aws_session_token = fauhrttgwargn=
aws_security_token = fasiouph3405

...
```
When I issue aws cli commands I specify which profile to use by way of the universal `--profile` option or I set the `AWS_PROFILE` env var to the name of the preferred profile. To avoid mistakes I never use a default profile, thus forcing an explicit profile to be defined. This is a pretty standard arrangement when you need to maintain multiple sessions.

Does lawsg support this sort of usage?

**Comment by reskin89** [comment]
@PeteW i would edit your comment, it has AWS keys which are sensitive data.

I would also expire those keys now

**Comment by PeteW** [comment]
Those aren't real keys

**Comment by reskin89** [comment]
Awesome :) can never be too careful

**Comment by reskin89** [comment]
To answer your Question, this issue was for this purpose. So just alter your AWS_PROFILE env var and you should be good to go

**Comment by PeteW** [comment]
@reskin89 thanks I wasnt familiar with the meaning of `AWS_SDK_LOAD_CONFIG` option. Then again, I'm not really familiar with go nor its conventions. I'll give this a try. If I dont write back assume its because things are working perfectly

**Comment by PeteW** [comment]
I couldnt get this working. Am I missing something?
```
PWeissbrod@mymachine
$ export AWS_PROFILE=myprofile

PWeissbrod@mymachine
$ export AWS_REGION=us-east-1

PWeissbrod@mymachine
$ lawsg
ERROR: Missing environment variable AWS_ACCESS_KEY_ID
```
Why would I need to specify the access key id or secret key when I've specified a profile?

**Comment by reskin89** [comment]
You definitely shouldn’t have to. What version are you running? If it’s 0.4.0 or later you may have found a bug
